services:
  flask_app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./database/database.db:/app/database.db
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus
      - alertmanager

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this in production!
      - GF_USERS_ALLOW_SIGN_UP=false

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
    - "9093:9093"
    volumes:
    - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
    - '--config.file=/etc/alertmanager/alertmanager.yml'
    - '--storage.path=/alertmanager'
    - '--web.external-url=http://localhost:9093'
    restart: unless-stopped
    networks:
    - monitoring

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - monitoring

volumes:
  database:
    driver: local
  grafana_data:
    driver: local

networks:
  monitoring:
    driver: bridge
