global:
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alert@localhost'
  smtp_require_tls: false

route:
  receiver: 'email-notifications'
  group_by: ['alertname']
  repeat_interval: 1m

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'alerts@example.com'
